CREATE TABLE PAIS(
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pais VARCHAR2(100),
    PRIMARY KEY(id_pais)
);

CREATE TABLE CIUDAD(
    id_ciudad NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ciudad VARCHAR2(100),
    fk_id_pais NUMBER,
    FOREIGN KEY (fk_id_pais) REFERENCES PAIS (id_pais),
    PRIMARY KEY(id_ciudad)
);

CREATE TABLE LENGUAJE(
    id_lenguaje NUMBER GENERATED BY DEFAULT AS IDENTITY,
    lenguaje_pelicula VARCHAR2(100),
    PRIMARY KEY(id_lenguaje)
);

CREATE TABLE CATEGORIA(
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    categoria_pelicula VARCHAR2(100),
    PRIMARY KEY(id_categoria)
);

CREATE TABLE CLASIFICACION(
    id_clasificacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    clasificacion VARCHAR2(100),
    PRIMARY KEY(id_clasificacion)
);

CREATE TABLE ACTOR(
    id_actor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_actor VARCHAR2(100),
    apellido_actor VARCHAR2(100),
    PRIMARY KEY(id_actor)
);

CREATE TABLE CLIENTE(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_cliente VARCHAR2(100),
    apellido_cliente VARCHAR2(100),
    correo_cliente VARCHAR2(100),
    cliente_activo VARCHAR2(100),
    fecha_creacion date,
    tienda_preferida VARCHAR2(100),
    direccion_cliente VARCHAR2(100),
    codigo_postal_cliente VARCHAR2(100),
    fk_id_ciudad NUMBER,
    FOREIGN KEY (fk_id_ciudad) REFERENCES ciudad (id_ciudad),
    PRIMARY KEY(id_cliente)  
);

CREATE TABLE TIENDA(
    id_tienda NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_tienda VARCHAR2(100),
    encargado_tienda VARCHAR2(100),
    direccion_tienda VARCHAR2(100),
    codigo_postal_tienda VARCHAR2(100),
    fk_id_ciudad NUMBER,
    FOREIGN KEY (fk_id_ciudad) REFERENCES ciudad (id_ciudad),
    PRIMARY KEY(id_tienda)  
);

CREATE TABLE EMPLEADO(
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_empleado VARCHAR2(100),
    apellido_empleado VARCHAR2(100),
    correo_empleado VARCHAR2(100),
    empleado_activo VARCHAR2(100),
    tienda_empleado VARCHAR2(100),
    usuario_empleado VARCHAR2(100),
    contrasena_empleado VARCHAR2(100),
    direccion_empleado VARCHAR2(100),
    codigo_postal_empleado VARCHAR2(100),
    fk_id_tienda NUMBER,
    fk_id_ciudad NUMBER,
    FOREIGN KEY (fk_id_tienda) REFERENCES tienda (id_tienda),
    FOREIGN KEY (fk_id_ciudad) REFERENCES ciudad (id_ciudad),
    PRIMARY KEY(id_empleado)  
);

CREATE TABLE PELICULA(
    id_pelicula NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_pelicula VARCHAR2(100),
    descripcion_pelicula VARCHAR2(200),
    anio_lazamiento INT,
    dias_renta INT,
    costo_renta FLOAT,
    duracion INT,
    costo_por_danio FLOAT,
    fk_id_clasificacion NUMBER,
    FOREIGN KEY (fk_id_clasificacion) REFERENCES clasificacion (id_clasificacion),
    PRIMARY KEY(id_pelicula)  
);

CREATE TABLE ALQUILER(
    id_alquiler NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha_renta date,
    fecha_retorno date,
    monto_a_pagar FLOAT,
    fecha_pago date,
    comision FLOAT,
    fk_id_cliente NUMBER,
    fk_id_empleado NUMBER,
    fk_id_pelicula NUMBER,
    FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    FOREIGN KEY (fk_id_empleado) REFERENCES empleado (id_empleado),
    FOREIGN KEY (fk_id_pelicula) REFERENCES pelicula (id_pelicula),
    PRIMARY KEY(id_alquiler)  
);

CREATE TABLE TIENDA_PELICULA(
    id_tienda_pelicula NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tienda_pelicula VARCHAR2(100),
    fk_id_tienda NUMBER,
    fk_id_pelicula NUMBER,
    FOREIGN KEY (fk_id_tienda) REFERENCES tienda (id_tienda),
    FOREIGN KEY (fk_id_pelicula) REFERENCES pelicula (id_pelicula),
    PRIMARY KEY(id_tienda_pelicula)  
);

CREATE TABLE DETALLE_ACTOR(
    fk_id_actor NUMBER,
    fk_id_pelicula NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion detalle actor', 
    FOREIGN KEY (fk_id_actor) REFERENCES actor(id_actor),
    FOREIGN KEY (fk_id_pelicula) REFERENCES pelicula(id_pelicula),
    PRIMARY KEY(fk_id_actor,fk_id_pelicula)  
);

CREATE TABLE DETALLE_LENGUAJE(
    fk_id_lenguaje NUMBER,
    fk_id_pelicula NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion detalle lenguaje', 
    FOREIGN KEY (fk_id_lenguaje) REFERENCES lenguaje(id_lenguaje),
    FOREIGN KEY (fk_id_pelicula) REFERENCES pelicula(id_pelicula),
    PRIMARY KEY(fk_id_lenguaje,fk_id_pelicula)  
);

CREATE TABLE DETALLE_CATEGORIA(
    fk_id_categoria NUMBER,
    fk_id_pelicula NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion detalle categoria', 
    FOREIGN KEY (fk_id_categoria) REFERENCES categoria(id_categoria),
    FOREIGN KEY (fk_id_pelicula) REFERENCES pelicula(id_pelicula),
    PRIMARY KEY(fk_id_categoria,fk_id_pelicula)  
);


-- ELIMINA TABLAS EN CASCADA 
/*
   SE ELIMINA EN EL ORDEN CONTRARIO AL QUE SE CREO. 
*/

DROP TABLE DETALLE_CATEGORIA;
DROP TABLE DETALLE_LENGUAJE;
DROP TABLE DETALLE_ACTOR;
DROP TABLE TIENDA_PELICULA;
DROP TABLE ALQUILER;
DROP TABLE PELICULA;
DROP TABLE EMPLEADO;
DROP TABLE TIENDA;
DROP TABLE CLIENTE;
DROP TABLE ACTOR;
DROP TABLE CLASIFICACION;
DROP TABLE CATEGORIA;
DROP TABLE LENGUAJE;
DROP TABLE CIUDAD;
DROP TABLE PAIS;
DROP TABLE TEMPORAL;


create table fechaPrueba (
    fecha date
)
select * from fechaPrueba
drop table fechaPrueba

SELECT * FROM TEMPORAL
SELECT COUNT (*) FROM TEMPORAL